version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  stocks:
    build:
      context: ./stocks
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
    depends_on:
      - mongodb
    networks:
      - app_network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/stocks

  capital-gains:
    build:
      context: ./capital-gains
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - stocks
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: